# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-06-13 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
